name: Cloud Scrapers (TCEs)

# Summary: Trigger the script manually from the Actions tab
on:
  workflow_dispatch: 

jobs:
  scrape_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 selenium

      - name: Run Scraper RJ
        run: python webscraper_rj.py
        continue-on-error: true

      - name: Run Scraper RS
        run: python webscraper_rs.py
        continue-on-error: true

      - name: Upload Data Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Dados_TCEs_Extraidos
          # This will capture all folders starting with "Dados_"
          path: Dados_*/ 
          retention-days: 7
